---

- name: Create /etc/default/unbound
  template:
    src: Debian.default.j2
    dest: /etc/default/unbound
    mode: 0644
    backup: yes
    validate: sh -n %s
  notify: Restart unbound

- name: Enable unbound
  service:
    name: "{{ unbound_service }}"
    enabled: yes
