---
# tasks file for ansible-role-unbound

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create unbound.conf
  template:
    src: unbound.conf.j2
    dest: "{{ unbound_conf_file }}"
    #validate: "unbound-checkconf %s"
  notify: Restart unbound

- name: Start unbound
  service:
    name: "{{ unbound_service }}"
    enabled: true
    state: started
